--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

-- Started on 2021-05-29 19:19:14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 203 (class 1259 OID 24749)
-- Name: candidates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.candidates (
    id integer NOT NULL,
    first_name character varying(35) NOT NULL,
    last_name character varying(35) NOT NULL,
    identity_number character varying(11) NOT NULL,
    birth_date date
);


ALTER TABLE public.candidates OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 25117)
-- Name: cities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cities (
    id integer NOT NULL,
    city_name character varying(50) NOT NULL
);


ALTER TABLE public.cities OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 24822)
-- Name: employee_confirm_employers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_confirm_employers (
    id integer NOT NULL,
    employer_id integer NOT NULL
);


ALTER TABLE public.employee_confirm_employers OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 24812)
-- Name: employee_confirms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_confirms (
    id integer NOT NULL,
    employee_id integer NOT NULL,
    is_confirmed boolean NOT NULL,
    confirm_date date
);


ALTER TABLE public.employee_confirms OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 24810)
-- Name: employee_confirms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee_confirms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_confirms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 24739)
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    id integer NOT NULL,
    first_name character varying(35) NOT NULL,
    last_name character varying(35) NOT NULL
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 24761)
-- Name: employers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employers (
    id integer NOT NULL,
    company_name character varying(255) NOT NULL,
    web_address character varying(50) NOT NULL,
    phone_number character varying(12) NOT NULL
);


ALTER TABLE public.employers OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 25152)
-- Name: job_advertisements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_advertisements (
    id integer NOT NULL,
    employer_id integer NOT NULL,
    job_title_id integer NOT NULL,
    city_id integer NOT NULL,
    description text NOT NULL,
    min_salary double precision,
    max_salary double precision,
    open_position_count integer NOT NULL,
    is_active boolean NOT NULL,
    last_apply_date date NOT NULL,
    create_date date NOT NULL
);


ALTER TABLE public.job_advertisements OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 25150)
-- Name: job_advertisements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_advertisements ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.job_advertisements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 24839)
-- Name: job_titles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_titles (
    id integer NOT NULL,
    title character varying(255)
);


ALTER TABLE public.job_titles OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 24837)
-- Name: job_titles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_titles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_titles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 201 (class 1259 OID 24732)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(320) NOT NULL,
    password character varying(25) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 24730)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 24780)
-- Name: verification_code_candidates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.verification_code_candidates (
    id integer NOT NULL,
    candidate_id integer NOT NULL
);


ALTER TABLE public.verification_code_candidates OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 24795)
-- Name: verification_code_employers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.verification_code_employers (
    id integer NOT NULL,
    employer_id integer NOT NULL
);


ALTER TABLE public.verification_code_employers OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 24773)
-- Name: verification_codes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.verification_codes (
    id integer NOT NULL,
    code character varying(38) NOT NULL,
    is_verified boolean NOT NULL,
    verified_date date
);


ALTER TABLE public.verification_codes OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 24771)
-- Name: verification_codes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.verification_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3081 (class 0 OID 24749)
-- Dependencies: 203
-- Data for Name: candidates; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3092 (class 0 OID 25117)
-- Dependencies: 214
-- Data for Name: cities; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.cities (id, city_name) VALUES (1, 'Adana');
INSERT INTO public.cities (id, city_name) VALUES (2, 'Adıyaman');
INSERT INTO public.cities (id, city_name) VALUES (3, 'Afyon');
INSERT INTO public.cities (id, city_name) VALUES (4, 'Ağrı');
INSERT INTO public.cities (id, city_name) VALUES (5, 'Amasya');
INSERT INTO public.cities (id, city_name) VALUES (6, 'Ankara');
INSERT INTO public.cities (id, city_name) VALUES (7, 'Antalya');
INSERT INTO public.cities (id, city_name) VALUES (8, 'Artvin');
INSERT INTO public.cities (id, city_name) VALUES (9, 'Aydın');
INSERT INTO public.cities (id, city_name) VALUES (10, 'Balıkesir');
INSERT INTO public.cities (id, city_name) VALUES (11, 'Bilecik');
INSERT INTO public.cities (id, city_name) VALUES (12, 'Bingöl');
INSERT INTO public.cities (id, city_name) VALUES (13, 'Bitlis');
INSERT INTO public.cities (id, city_name) VALUES (14, 'Bolu');
INSERT INTO public.cities (id, city_name) VALUES (15, 'Burdur');
INSERT INTO public.cities (id, city_name) VALUES (16, 'Bursa');
INSERT INTO public.cities (id, city_name) VALUES (17, 'Çanakkale');
INSERT INTO public.cities (id, city_name) VALUES (18, 'Çankırı');
INSERT INTO public.cities (id, city_name) VALUES (19, 'Çorum');
INSERT INTO public.cities (id, city_name) VALUES (20, 'Denizli');
INSERT INTO public.cities (id, city_name) VALUES (21, 'Diyarbakır');
INSERT INTO public.cities (id, city_name) VALUES (22, 'Edirne');
INSERT INTO public.cities (id, city_name) VALUES (23, 'Elazığ');
INSERT INTO public.cities (id, city_name) VALUES (24, 'Erzincan');
INSERT INTO public.cities (id, city_name) VALUES (25, 'Erzurum');
INSERT INTO public.cities (id, city_name) VALUES (26, 'Eskişehir');
INSERT INTO public.cities (id, city_name) VALUES (27, 'Gaziantep');
INSERT INTO public.cities (id, city_name) VALUES (28, 'Giresun');
INSERT INTO public.cities (id, city_name) VALUES (29, 'Gümüşhane');
INSERT INTO public.cities (id, city_name) VALUES (30, 'Hakkari');
INSERT INTO public.cities (id, city_name) VALUES (31, 'Hatay');
INSERT INTO public.cities (id, city_name) VALUES (32, 'Isparta');
INSERT INTO public.cities (id, city_name) VALUES (33, 'Mersin');
INSERT INTO public.cities (id, city_name) VALUES (34, 'İstanbul');
INSERT INTO public.cities (id, city_name) VALUES (35, 'İzmir');
INSERT INTO public.cities (id, city_name) VALUES (36, 'Kars');
INSERT INTO public.cities (id, city_name) VALUES (37, 'Kastamonu');
INSERT INTO public.cities (id, city_name) VALUES (38, 'Kayseri');
INSERT INTO public.cities (id, city_name) VALUES (39, 'Kırklareli');
INSERT INTO public.cities (id, city_name) VALUES (40, 'Kırşehir');
INSERT INTO public.cities (id, city_name) VALUES (41, 'Kocaeli');
INSERT INTO public.cities (id, city_name) VALUES (42, 'Konya');
INSERT INTO public.cities (id, city_name) VALUES (43, 'Kütahya');
INSERT INTO public.cities (id, city_name) VALUES (44, 'Malatya');
INSERT INTO public.cities (id, city_name) VALUES (45, 'Manisa');
INSERT INTO public.cities (id, city_name) VALUES (46, 'K.Maraş');
INSERT INTO public.cities (id, city_name) VALUES (47, 'Mardin');
INSERT INTO public.cities (id, city_name) VALUES (48, 'Muğla');
INSERT INTO public.cities (id, city_name) VALUES (49, 'Muş');
INSERT INTO public.cities (id, city_name) VALUES (50, 'Nevşehir');
INSERT INTO public.cities (id, city_name) VALUES (51, 'Niğde');
INSERT INTO public.cities (id, city_name) VALUES (52, 'Ordu');
INSERT INTO public.cities (id, city_name) VALUES (53, 'Rize');
INSERT INTO public.cities (id, city_name) VALUES (54, 'Sakarya');
INSERT INTO public.cities (id, city_name) VALUES (55, 'Samsun');
INSERT INTO public.cities (id, city_name) VALUES (56, 'Siirt');
INSERT INTO public.cities (id, city_name) VALUES (57, 'Sinop');
INSERT INTO public.cities (id, city_name) VALUES (58, 'Sivas');
INSERT INTO public.cities (id, city_name) VALUES (59, 'Tekirdağ');
INSERT INTO public.cities (id, city_name) VALUES (60, 'Tokat');
INSERT INTO public.cities (id, city_name) VALUES (61, 'Trabzon');
INSERT INTO public.cities (id, city_name) VALUES (62, 'Tunceli');
INSERT INTO public.cities (id, city_name) VALUES (63, 'Şanlıurfa');
INSERT INTO public.cities (id, city_name) VALUES (64, 'Uşak');
INSERT INTO public.cities (id, city_name) VALUES (65, 'Van');
INSERT INTO public.cities (id, city_name) VALUES (66, 'Yozgat');
INSERT INTO public.cities (id, city_name) VALUES (67, 'Zonguldak');
INSERT INTO public.cities (id, city_name) VALUES (68, 'Aksaray');
INSERT INTO public.cities (id, city_name) VALUES (69, 'Bayburt');
INSERT INTO public.cities (id, city_name) VALUES (70, 'Karaman');
INSERT INTO public.cities (id, city_name) VALUES (71, 'Kırıkkale');
INSERT INTO public.cities (id, city_name) VALUES (72, 'Batman');
INSERT INTO public.cities (id, city_name) VALUES (73, 'Şırnak');
INSERT INTO public.cities (id, city_name) VALUES (74, 'Bartın');
INSERT INTO public.cities (id, city_name) VALUES (75, 'Ardahan');
INSERT INTO public.cities (id, city_name) VALUES (76, 'Iğdır');
INSERT INTO public.cities (id, city_name) VALUES (77, 'Yalova');
INSERT INTO public.cities (id, city_name) VALUES (78, 'Karabük');
INSERT INTO public.cities (id, city_name) VALUES (79, 'Kilis');
INSERT INTO public.cities (id, city_name) VALUES (80, 'Osmaniye');
INSERT INTO public.cities (id, city_name) VALUES (81, 'Düzce');


--
-- TOC entry 3089 (class 0 OID 24822)
-- Dependencies: 211
-- Data for Name: employee_confirm_employers; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3088 (class 0 OID 24812)
-- Dependencies: 210
-- Data for Name: employee_confirms; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3080 (class 0 OID 24739)
-- Dependencies: 202
-- Data for Name: employees; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3082 (class 0 OID 24761)
-- Dependencies: 204
-- Data for Name: employers; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3094 (class 0 OID 25152)
-- Dependencies: 216
-- Data for Name: job_advertisements; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3091 (class 0 OID 24839)
-- Dependencies: 213
-- Data for Name: job_titles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.job_titles (id, title) VALUES (1, 'Software Developer');


--
-- TOC entry 3079 (class 0 OID 24732)
-- Dependencies: 201
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3085 (class 0 OID 24780)
-- Dependencies: 207
-- Data for Name: verification_code_candidates; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3086 (class 0 OID 24795)
-- Dependencies: 208
-- Data for Name: verification_code_employers; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3084 (class 0 OID 24773)
-- Dependencies: 206
-- Data for Name: verification_codes; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3100 (class 0 OID 0)
-- Dependencies: 209
-- Name: employee_confirms_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employee_confirms_id_seq', 1, false);


--
-- TOC entry 3101 (class 0 OID 0)
-- Dependencies: 215
-- Name: job_advertisements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.job_advertisements_id_seq', 1, false);


--
-- TOC entry 3102 (class 0 OID 0)
-- Dependencies: 212
-- Name: job_titles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.job_titles_id_seq', 1, true);


--
-- TOC entry 3103 (class 0 OID 0)
-- Dependencies: 200
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- TOC entry 3104 (class 0 OID 0)
-- Dependencies: 205
-- Name: verification_codes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.verification_codes_id_seq', 1, false);


--
-- TOC entry 2910 (class 2606 OID 24753)
-- Name: candidates pk_candidates; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT pk_candidates PRIMARY KEY (id);


--
-- TOC entry 2932 (class 2606 OID 25121)
-- Name: cities pk_cities; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT pk_cities PRIMARY KEY (id);


--
-- TOC entry 2926 (class 2606 OID 24826)
-- Name: employee_confirm_employers pk_employee_confirm_employers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_confirm_employers
    ADD CONSTRAINT pk_employee_confirm_employers PRIMARY KEY (id);


--
-- TOC entry 2924 (class 2606 OID 24816)
-- Name: employee_confirms pk_employee_confirms; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_confirms
    ADD CONSTRAINT pk_employee_confirms PRIMARY KEY (id);


--
-- TOC entry 2908 (class 2606 OID 24743)
-- Name: employees pk_employees; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT pk_employees PRIMARY KEY (id);


--
-- TOC entry 2914 (class 2606 OID 24765)
-- Name: employers pk_employers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT pk_employers PRIMARY KEY (id);


--
-- TOC entry 2934 (class 2606 OID 25159)
-- Name: job_advertisements pk_job_advertisements; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_advertisements
    ADD CONSTRAINT pk_job_advertisements PRIMARY KEY (id);


--
-- TOC entry 2928 (class 2606 OID 24843)
-- Name: job_titles pk_job_titles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_titles
    ADD CONSTRAINT pk_job_titles PRIMARY KEY (id);


--
-- TOC entry 2904 (class 2606 OID 24736)
-- Name: users pk_users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT pk_users PRIMARY KEY (id);


--
-- TOC entry 2920 (class 2606 OID 24784)
-- Name: verification_code_candidates pk_verification_code_candidates; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_code_candidates
    ADD CONSTRAINT pk_verification_code_candidates PRIMARY KEY (id);


--
-- TOC entry 2922 (class 2606 OID 24799)
-- Name: verification_code_employers pk_verification_code_employers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_code_employers
    ADD CONSTRAINT pk_verification_code_employers PRIMARY KEY (id);


--
-- TOC entry 2916 (class 2606 OID 24777)
-- Name: verification_codes pk_verification_codes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_codes
    ADD CONSTRAINT pk_verification_codes PRIMARY KEY (id);


--
-- TOC entry 2912 (class 2606 OID 24755)
-- Name: candidates uc_candidates_identity_number; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT uc_candidates_identity_number UNIQUE (identity_number);


--
-- TOC entry 2930 (class 2606 OID 24845)
-- Name: job_titles uc_job_titles_title; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_titles
    ADD CONSTRAINT uc_job_titles_title UNIQUE (title);


--
-- TOC entry 2906 (class 2606 OID 24738)
-- Name: users uc_users_email; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uc_users_email UNIQUE (email);


--
-- TOC entry 2918 (class 2606 OID 24779)
-- Name: verification_codes uc_verification_codes_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_codes
    ADD CONSTRAINT uc_verification_codes_code UNIQUE (code);


--
-- TOC entry 2936 (class 2606 OID 24756)
-- Name: candidates fk_candidates_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT fk_candidates_users FOREIGN KEY (id) REFERENCES public.users(id);


--
-- TOC entry 2943 (class 2606 OID 24827)
-- Name: employee_confirm_employers fk_employee_confirm_employers_employee_confirms; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_confirm_employers
    ADD CONSTRAINT fk_employee_confirm_employers_employee_confirms FOREIGN KEY (id) REFERENCES public.employee_confirms(id);


--
-- TOC entry 2944 (class 2606 OID 24832)
-- Name: employee_confirm_employers fk_employee_confirm_employers_employers; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_confirm_employers
    ADD CONSTRAINT fk_employee_confirm_employers_employers FOREIGN KEY (employer_id) REFERENCES public.employers(id);


--
-- TOC entry 2942 (class 2606 OID 24817)
-- Name: employee_confirms fk_employee_confirms_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_confirms
    ADD CONSTRAINT fk_employee_confirms_employee_id FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- TOC entry 2935 (class 2606 OID 24744)
-- Name: employees fk_employees_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk_employees_users FOREIGN KEY (id) REFERENCES public.users(id);


--
-- TOC entry 2937 (class 2606 OID 24766)
-- Name: employers fk_employers_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT fk_employers_users FOREIGN KEY (id) REFERENCES public.users(id);


--
-- TOC entry 2947 (class 2606 OID 25170)
-- Name: job_advertisements fk_job_advertisements_cities; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_advertisements
    ADD CONSTRAINT fk_job_advertisements_cities FOREIGN KEY (city_id) REFERENCES public.cities(id);


--
-- TOC entry 2945 (class 2606 OID 25160)
-- Name: job_advertisements fk_job_advertisements_employers; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_advertisements
    ADD CONSTRAINT fk_job_advertisements_employers FOREIGN KEY (employer_id) REFERENCES public.employers(id);


--
-- TOC entry 2946 (class 2606 OID 25165)
-- Name: job_advertisements fk_job_advertisements_job_titles; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_advertisements
    ADD CONSTRAINT fk_job_advertisements_job_titles FOREIGN KEY (job_title_id) REFERENCES public.job_titles(id);


--
-- TOC entry 2939 (class 2606 OID 24790)
-- Name: verification_code_candidates fk_verification_code_candidates_candidates; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_code_candidates
    ADD CONSTRAINT fk_verification_code_candidates_candidates FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- TOC entry 2938 (class 2606 OID 24785)
-- Name: verification_code_candidates fk_verification_code_candidates_verification_codes; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_code_candidates
    ADD CONSTRAINT fk_verification_code_candidates_verification_codes FOREIGN KEY (id) REFERENCES public.verification_codes(id);


--
-- TOC entry 2941 (class 2606 OID 24805)
-- Name: verification_code_employers fk_verification_code_employers_employers; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_code_employers
    ADD CONSTRAINT fk_verification_code_employers_employers FOREIGN KEY (employer_id) REFERENCES public.employers(id);


--
-- TOC entry 2940 (class 2606 OID 24800)
-- Name: verification_code_employers fk_verification_code_employers_verification_codes; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.verification_code_employers
    ADD CONSTRAINT fk_verification_code_employers_verification_codes FOREIGN KEY (id) REFERENCES public.verification_codes(id);


-- Completed on 2021-05-29 19:19:14

--
-- PostgreSQL database dump complete
--

